intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}
import test_libs += doctest%lib{doctest}

./: lib{convertible}: libul{convertible}: {hxx ixx txx cxx}{** -**.test... -doctest_define_main -version} \
  hxx{version} $impl_libs $intf_libs

# Unit tests.
# Create precompiled doctest_main lib

lib{doctest_main}: cxx{doctest_define_main} $test_libs
{
  cxx.export.libs = $test_libs
}

exe{*.test}:
{
  test = true
  install = false
}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n} lib{doctest_main}
  $d/exe{$n}: libul{convertible}: bin.whole = false
}

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DCONVERTIBLE_STATIC_BUILD
objs{*}: cxx.poptions += -DCONVERTIBLE_SHARED_BUILD

# Export options.
#
lib{convertible}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{convertible}: cxx.export.poptions += -DCONVERTIBLE_STATIC
libs{convertible}: cxx.export.poptions += -DCONVERTIBLE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{convertible}: bin.lib.version = @"-$version.project_id"
else
  lib{convertible}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the convertible/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/convertible/
  install.subdirs = true
}
